### ISSUE TITLE
When I export a Symbol and then import it to new Builder instance, the symbol won't work

### ISSUE THREAD

**Issue by JefferyReidKnowde** [BuilderIO/builder#41] opened 2020-01-16 21:08 UTC
When I export a Symbol and then import it to new Builder instance, the symbol won't work

Steps to reproduce

- Create a symbol with editable text and images
- Export is using "Download content as JSON"
- Login to a new instance of builder (new account)
- Import this using ""Upload builder JSON file"
- Create a new page
- Select this new symbol and add it to a page

Result
- Symbol is not added to page.

**Comment by JefferyReidKnowde** [comment] 2020-01-16 21:10
Here's an example page
https://builder.io/content/d4a3c75d248b4cedbcb61485ba0df9ba

**Comment by steve8708** [comment] 2020-01-17 16:28
This is likely because the symbol references a content entry from the other Builder instance, which isn't shared across organizations/accounts. So in order to do what you want, you'll need to copy the symbol entry over to the other account, then add a symbol block to a page and choose that new entry you made in that same account

Another option for moving more quickly is "inlining" the symbol. Aka on the original account, click edit for the symbol and choose "make inline". That removes the reference to the original content entry (no longer stays in sync) and copies the contents there inline. You can copy an inline symbol across since it no longer references any other entries

**Comment by JefferyReidKnowde** [comment] 2020-01-17 16:44
OK. That doesn't sound like it would work since inlining removes the inputs and bindings from the symbol, right?

**Comment by steve8708** [comment] 2020-01-17 16:46
Not at all - inlining preserves all of that

Note just one difference - to edit those things again you just need to make sure you do it from the "show advanced" section of the options tab when clicking the symbol, rather than in the "data" tab of the original entry

**Comment by steve8708** [comment] 2020-01-17 23:23
Going to close this out as the expected behavior but lmk if anything above doesn't make sense

**Closed by steve8708** 2020-01-17 23:23 UTC
