### ISSUE TITLE
Image override with the Cloudinary plugin

### ISSUE THREAD

**Issue by donnieblando** [BuilderIO/builder#33] opened 2020-01-08 17:15 UTC
When more than one image is added to the page through the Cloudinary plugin, the last one to be added **overrides all the other ones**

**Comment by steve8708** [comment] 2020-01-08 19:52
this is most likely in the plugin code from Jacob - pinged him to see if he can take a peek, can look on our end too if it looks to him like the source of the issue is on our / the platform side (rather than the plugin)

**Comment by ca136** [comment] 2020-01-09 21:40
Thanks for sending https://github.com/BuilderIO/builder/pull/35 @donnieblando!

**Comment by steve8708** [comment] 2020-01-10 18:27
Fixed via #35 👍

**Closed by steve8708** 2020-01-10 18:27 UTC
