### ISSUE TITLE
[Vue3] TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css"

### ISSUE THREAD

**Issue by behzadsp** [BuilderIO/builder#2921] opened 2024-01-18 09:04 UTC
**Describe the bug**
I am experiencing a `TypeError [ERR_UNKNOWN_FILE_EXTENSION]` with the latest version (0.10.0) in my Vue 3 + InertiaJS + Laravel project. The error points to an unknown file extension ".css" for the file located at `/node_modules/@builder.io/sdk-vue/vue3/lib/node/style.css`.

**To Reproduce**
1. Include Builder.io in a Vue 3 + InertiaJS + Laravel project with the latest version (0.10.0).
2. Run the SSR server.
3. Visit the page created via Builder.io
4. Encounter the `TypeError [ERR_UNKNOWN_FILE_EXTENSION]` with the mentioned file.

**Expected behavior**
I expected the SSR server to run without errors related to unknown file extensions.

**Screenshots**
<img width="814" alt="image" src="https://github.com/BuilderIO/builder/assets/58994682/f460518b-26c1-4154-805f-45b79d7e95c0">

**Additional context**
I have integrated Builder.io version 0.10.0 into my project. Interestingly, prior to version 0.8.0, this specific error did not occur. However, it's worth noting that in versions preceding 0.8.0, I encountered issues with the proper functioning of SSR (Server-Side Rendering).

**Comment by ps-20x** [comment] 2024-01-18 11:53
Duplicate of https://github.com/BuilderIO/builder/issues/2917

**Closed** 2024-01-18 14:08 UTC
