### ISSUE TITLE
When you daisy chain symbols (nest symbol into symbol), not all the configurable options are passing through

### ISSUE THREAD

**Issue by JefferyReidKnowde** [BuilderIO/builder#26] opened 2020-01-03 20:21 UTC
When you daisy chain symbols (nest symbol into symbol), not all the configurable options are passing through.

Steps to reproduce
* Create a symbol (a button) with text input, bg color, etc (the "child" symbol)
* Add that to another symbol, (the "parent" symbol), with additional configurable options
* Add the parent symbol to a page
* Select the parent symbol on the page, choose Options and notice that not all the configurable options from the child symbol are exposed

**Comment by steve8708** [comment] 2020-01-24 03:00
hey @JefferyReidKnowde if I follow correctly, this is the expected behavior - but let me first verify I understand fully

when you create a symbol (the parent) and add a symbol within that (the child) - you can define inputs on this symbol (the parent). then when you add that symbol to a page or anywhere else, that symbols inputs should be available as user facing options. if you want the child symbol options exposed from adding the parent to pages, you'd need to make additional inputs on the parent and pass those down to the child (e.g. if you want child input named "text" to be exposed to users dropping in the parent to a page/etc - you'd need to create a "text" input for the parent, then bind that to the "text" property of the child). i.e. all options of nested symbol don't automatically bubble up to the parent (this is an interesting possible feature idea, would just have to think through any drawbacks this could possibly have, e.g. cases where maybe that's not expected and could be confusing)

anyway, if what I describe above is not what you are saying or I am misunderstanding what you are doing vs expecting please just let me know

and thanks as always for your details reports and feedback!

**Comment by steve8708** [comment] 2020-01-24 03:01
also, I am misunderstanding - if you can link us to an example of the above that you did in Builder.io and we can see the wrong behavior in practice happy to take a look at the link, as the example may help clarify for me

**Comment by ca136** [comment] 2020-01-31 23:51
@JefferyReidKnowde going to close this since it looks like this is currently supported. I sent an email with more details, but will be happy to re-open if we're misunderstanding what you need!

**Closed by ca136** 2020-01-31 23:51 UTC
Labels: bug
