### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by FutureFutureTo** [BuilderIO/builder#2304] opened 2023-05-29 16:28 UTC
**Screenshots**
<img width="1082" alt="Screen Shot 2023-05-29 at 12 26 30 PM" src="https://github.com/BuilderIO/builder/assets/13020134/ff97a02c-f4a0-4199-b7e3-a714e5ad76ab">

**Additional context**
I created posts in builder and am following the NextJs guide. Any one else get this?

**Comment by mrkoreye** [comment] 2023-05-30 17:58
Hi @FutureFutureTo, are you using the new app router with nextjs, or using the pages router? That can make some differences in exactly how you integrate. Which nextjs guide are you following? Would it be possible to share your code repo or a small reproduction of a nextjs app integrated with builder that has this issue?

**Comment by samijaber** [comment] 2024-10-02 14:46
@FutureFutureTo  Are you still experiencing this issue? I am closing this issue due to staleness, but please feel free to reopen if the problem persists.

**Closed by samijaber** 2024-10-02 14:46 UTC
