### ISSUE TITLE
React: <BuilderComponent> doesn't rerender when user attributes change

### ISSUE THREAD

**Issue by jamesarosen** [BuilderIO/builder#156] opened 2020-04-29 21:47 UTC
We have a basic Builder component:
```jsx
<BuilderComponent model="home-pages" />
```

If we call `builder.setUserAttributes` _before_ this renders, it will pass the correct attributes to the Builder API and render the correct content.

If we then call `builder.setUserAttributes` _after_ this renders (e.g. if the user signs in), it doesn't show the new content.

Problem 1: Builder doesn't fetch new content from the API. We can tell this is a problem because there's nothing in the network tab when we call `builder.setUserAttributes`.

Problem 2: Builder fetches new content from the API, but the component doesn't update. We can tell this is a problem because even if we manually fetch new content and pass it into `<BuilderComponent>`, it doesn't update:

```jsx
// doesn't work:
function MyComponent() {
  const [content, setContent] = useState(null)

  useEffect(() => {
    builder.get('home-pages').promise().then(setContent)
  })

  return <BuilderContent model="home-pages" content={content} />
}

// works:
function MyComponentWithKeyUpdate() {
  const [content, setContent] = useState(null)

  useEffect(() => {
    builder.get('home-pages').promise().then(setContent)
  })

  return <BuilderComponent model="home-pages" content={content} key={content.id} />
}
```

**Comment by jamesarosen** [comment] 2020-04-29 23:43
We can currently work around attribute problem in application-land by monkey-patching `setUserAttributes`:

```jsx
import EventEmitter from 'eventemitter3'
import { Builder }, BuilderComponent from '@builder.io/react'
import { useEffect, useState }, React from 'react'

const EE = new EventEmitter()
const EVENT_NAME = 'Builder.prototype.setUserAttributes'

const originalSetUserAttributes = Builder.prototype.setUserAttributes

Builder.prototype.setUserAttributes = function setUserAttributes(attrs) {
  const result = originalSetUserAttributes.call(this, attrs)
  EE.emit(EVENT_NAME, attrs)
  return result
}

export default function MyBuilderComponent(props) {
  const [key, setKey] = useState(0)


  useEffect(() => {
    const updateKey = () => setKey(key + 1)
    EE.on(EVENT_NAME, updateKey)
    return () => EE.off(EVENT_NAME, updateKey)
  })

  return <BuilderComponent {...props} key={key} />
}
```

**Comment by steve8708** [comment] 2020-04-30 21:56
Thanks for the thorough ticket @jamesarosen 

Just published `@builder.io/react@1.1.16-alpha.10` that adds an observable for listening to user attributes changing as:

```tsx
builder.userAttributesChanged.subscribe(handler)
```

As well as properly handling new content being passed in

If you run into any further issues with this version or newer just let us know!

**Comment by steve8708** [comment] 2020-05-05 19:16
this is now officially released with `@builder.io/react@1.1.16`

**Comment by antonhalim** [comment] 2020-05-05 19:17
Nice, thanks!

**Comment by jamesarosen** [comment] 2020-05-05 19:25
> Just published @builder.io/react@1.1.16-alpha.10 that adds an observable for listening to user attributes changing

We don't actually need the observer if `<BuilderComponent>` automatically updates when user attributes change.

**Comment by steve8708** [comment] 2020-05-05 19:35
so with these updates the components don't all update on user attributes changing, we added the observer and the correct behavior for changing content when the `conent` prop changes so that it can be in peoples control if they want the content to automatically update or not

that said this can be done more elegantly with a simple prop to handle this automatically, e.g. `updateOnAttribtuesChange` or perhaps a global config/setting for this

if that would be helpful lmk and we can add ^

**Comment by jamesarosen** [comment] 2020-05-05 19:41
With the observer, we can at least wrap `<BuilderComponent>` with our own version that does update automatically:
```jsx
export default function MyBuilderComponent(props) {
  const [userAttributesVersion, setUserAttributesVersion] = useState(0)

  useEffect(() => {
    function incrementUserAttributesVersion() {
      setUserAttributesVersion(userAttributesVersion + 1)
    }

    builder.userAttributesChanged.subscribe(incrementUserAttributesVersion)

    return () => { builder.userAttributesChanged.unsubscribe(incrementUserAttributesVersion) })
  })

  return <BuilderComponent {...props} key={userAttributesVersion} />
}
```

**Comment by antonhalim** [comment] 2020-05-05 19:51
That could work, but does `builder.userAttributesChanged` has `unsubscribe` API?

**Comment by steve8708** [comment] 2020-05-05 19:55
Yeah @antonhalim it follows the [ES Observable](https://github.com/tc39/proposal-observable) so you just do 

```ts
const subscription = builder.userAttributesChanged.subscribe(incrementUserAttributesVersion)

// when you need to unsubscribe
subscribption.unsubscribe()
```

**Comment by antonhalim** [comment] 2020-05-05 21:47
Not sure why where's the pitfall, but I ran into issue where the callback is still called after `unsubscribed()` when unmounting.

```jsx
class SomeComponent extends React.Component {
  componentDidMount() {
    this.fetchBuilderPage()
    this.builderSubscription = builder.userAttributesChanged.subscribe(
      this.fetchBuilderPage,
    )
  }
  fetchBuilderPage = async () => {
    if (this.props.gender !== 'male') return

    // Don't know why this function is still called after unsubscribption in unmount
    // I ended up with this one extra line of logic.
    if (this.builderSubscription.unsubscribed) return

    const builderData = await builder.get('homepage').promise()

    if (builderData) {
      this.setState({ builderPage: builderData })
    }
  }
  componentWillUnmount() {
    // Unsubscribe builder subscription on unmounting
    this.builderSubscription.unsubscribe()
  }

  render() {
    return <BuilderComponent model="homepage" content={this.state.builderPage} />
  }
}

```

**Comment by teleaziz** [comment] 2020-05-05 21:58
Thanks for reporting Anton, looking into it.

**Comment by antonhalim** [comment] 2020-05-05 22:20
Thanks Aziz! It happens when the URL change, e.g. from clicking a link. Not sure if this is Builder's issue or Observerable.

**Comment by steve8708** [comment] 2020-05-06 16:08
btw we found a bug that with the last release with symbols not displaying in the editor, so when you upgrade I'd recommend using `@builder.io/react@1.1.17` :) 

will also release again if needed when we find what might be causing unsubscribing to not always work

**Closed** 2020-05-06 20:43 UTC

**Comment by antonhalim** [comment] 2020-05-07 04:55
Sorry I have to come back to this, it seems there is still regression with the issue. Here is the code example I ran on my end.
```jsx
import React, { Component } from 'react'
import { builder, BuilderComponent } from '@builder.io/react'

export default class Index extends Component {
  state = {
    builderPage: null,
  }

  componentDidMount() {
    this.builderSubscription = builder.userAttributesChanged.subscribe(
      this.callingSubscription,
    )
  }

  componentWillUnmount() {
    // Unsubscribe builder subscription
    console.log('Unsubscribe...')
    this.builderSubscription.unsubscribe()
  }

  callingSubscription = async () => {
    console.log('Calling subscription....')
    console.log(
      'isBuilderSubscription unsubscribed ',
      this.builderSubscription.unsubscribed,
    )
  }

  render() {
    return <BuilderComponent model="some-model" />
  }
}
```
Here is the console log:
// Calling subscription....
// isBuilderSubscription unsubscribed  false

I then click/navigate away from the builder page...
// Unsubscribe...
// Calling subscription....
// isBuilderSubscription unsubscribed  true

I can avoid this by adding a check whether `this.builderSubscription` is either unsubscribed or not to execute `callingSubscription`.
`if (this.builderSubscription.unsubscribed) return`
I would think that is not needed, `callingSubscription` function shouldn't be called again after unsubscribing. I also notice this only happens to the first subscription callback. If I have multiple subscription, the second unsubscribed and is not called after unsubscribed.

**Comment by ca136** [comment] 2020-05-07 15:14
Thanks for the additional details, definitely sounds like the bug we found yesterday! I was able to test the fix locally by npm-linking the SDKs, and the subscription wasn't firing after the component was unmounted. We haven't released anything since the fix was merged, but should have a pre-release version of the SDK that you can test soon.

**Comment by steve8708** [comment] 2020-05-07 15:52
Just released the latest - this should be fixed in `@builder.io/react@1.1.18`

**Comment by antonhalim** [comment] 2020-05-07 16:53
I should've mentioned that I tested in `@builder.io/react@1.1.17`.
Thank you so much folks, I really appreciate all the work and attention here 👏
