### ISSUE TITLE
Error when running in latest Next.js version with middleware

### ISSUE THREAD

**Issue by kevva** [BuilderIO/builder#610] opened 2021-10-31 13:46 UTC
On Next.js v12, you'll get this when adding middleware to your app:

```
`eval` not allowed in Middleware pages/_middleware
error - node_modules/@builder.io/sdk/dist/index.esm.js?b22a (919:0) @ <unknown>
TypeError: Cannot read property 'parse' of null
```

This points to [this line](https://github.com/BuilderIO/builder/blob/d340df65bddc981f0826e047ae58a0d00c5c35f0/packages/core/src/builder.class.ts#L89) which makes use of `serverOnlyRequire`. The problem is that that function [makes use of `eval`](https://github.com/BuilderIO/builder/blob/d340df65bddc981f0826e047ae58a0d00c5c35f0/packages/core/src/functions/server-only-require.function.ts#L6) to detect `require` and since Next.js doesn't allow `eval` in middleware it'll throw no matter what so I think another non-eval check is needed.

**Comment by kevva** [comment] 2021-10-31 14:56
This happens because I import somethings that imports `@builder/react` in my middleware. If I remove that import or convert it to a dynamic import it works so I can work around it. But regardless, maybe there's a better alternative to using `eval`?

**Comment by kevva** [comment] 2021-11-03 23:43
@teleaziz , was this fixed by https://github.com/BuilderIO/builder/commit/7eab05b267f55e89a76f92c84e838492bbe1a794?

**Comment by kevva** [comment] 2021-11-04 11:33
This issue also happens if you try to run Next.js with [server components](https://nextjs.org/blog/next-12#react-server-components). That one is harder to work around.

**Comment by teleaziz** [comment] 2021-11-08 17:02
Hi @kevva thanks for reporting this issue, do you have any kind of reproduction steps for the issue with nextjs server components?

For the middleware it looks like it's a [hard limit](https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis) as it only support a subset of nodejs API, what's the use case for using the react sdk in the middleware function?

**Comment by end0cr1ne** [comment] 2022-08-06 10:15
Running a hydrogen storefront using vercel's edge functions

**Comment by rista404** [comment] 2022-08-17 21:43
Same issue running a hydrogen storefront on vercel's edge functions.

**Comment by terza98** [comment] 2022-08-18 05:44
This should be really looked into asap, same issue over here

**Comment by teleaziz** [comment] 2022-09-09 17:53
This is fixed and released in the latest stable version please use `@builder.io/react@2.0.5` to get the fix, thank you for reporting

**Closed by teleaziz** 2022-09-09 17:53 UTC
